[versions]
agp = "8.2.0-alpha08"
#al = "8.2.0-alpha08"
constraintlayout = "2.2.0-alpha10"
dexkit = "1.1.8"
ezxhelper = "2.0.5"
hidden-api-bypass = "4.3"
jpinyin = "1.0.1"
xposed-api = "82"
kotlin = "1.9.0-Beta"
core-ktx = "1.12.0-alpha05"

[libraries]
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
dexkit = { module = "org.luckypray:DexKit", version.ref = "dexkit" }
ezxhelper = { module = "com.github.kyuubiran:EzXHelper", version.ref = "ezxhelper" }
jpinyin = { module = "io.github.ranlee1:jpinyin", version.ref = "jpinyin" }
lsposed-hidden-api-bypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hidden-api-bypass" }
xposed = { module = "de.robv.android.xposed:api", version.ref = "xposed-api" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
#androidLibrary = { id = "com.android.library", version.ref = "al" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[bundles]

